Use a POD-valid installed-command proxy

diff --git a/investigations/mmdebstrap-autopkgtest-1141078/installed-command-wrapper.patch b/investigations/mmdebstrap-autopkgtest-1141078/installed-command-wrapper.patch
--- a/investigations/mmdebstrap-autopkgtest-1141078/installed-command-wrapper.patch
+++ b/investigations/mmdebstrap-autopkgtest-1141078/installed-command-wrapper.patch
@@ -1,27 +1,44 @@
 diff --git a/debian/tests/testsuite b/debian/tests/testsuite
 --- a/debian/tests/testsuite
 +++ b/debian/tests/testsuite
-@@ -146,6 +146,14 @@ cat << END > ./mmdebstrap
- exit(1)
- END
- 
-+# Exercise the installed command while keeping coverage.sh from applying the
-+# source tree's style gate to a package built with an older perltidy release.
-+cat << 'END' > ./mmdebstrap-under-test
-+#!/bin/sh
-+exec /usr/bin/mmdebstrap "$@"
-+END
-+chmod 0755 ./mmdebstrap-under-test
+@@ -140,11 +140,27 @@ trap "kill $HTTPD_PID" INT QUIT TERM EXIT
+-# create a fake mmdebstrap file in the current directory that coverage.sh can
+-# copy
+-cat << END > ./mmdebstrap
++# create a formatted proxy in the current directory so that coverage.sh checks
++# this source while every behavioral invocation reaches the installed package
++cat << 'END' > ./mmdebstrap
+ #!/usr/bin/perl
+ use strict;
+ use warnings;
+-exit(1)
++use English qw(-no_match_vars);
 +
++exec '/usr/bin/mmdebstrap', @ARGV
++  or die "cannot exec /usr/bin/mmdebstrap: $OS_ERROR\n";
++
++__END__
++
++=head1 NAME
++
++mmdebstrap - proxy to the installed package under test
++
++=head1 DESCRIPTION
++
++Forwards all arguments to F</usr/bin/mmdebstrap>.
++
++=cut
+ END
++chmod 0755 ./mmdebstrap
+ 
  # must not be used during testing -- installed version must be used instead
  cat << END > ./tarfilter
- #!/usr/bin/env python3
-@@ -175,7 +183,7 @@ fi
+@@ -175,7 +191,7 @@ fi
  # HAVE_QEMU=no because there is no kvm kernel module
  # HAVE_BINFMT=no because there is no binfmt_misc kernel module
  ret=0
 -timeout $TIMEOUT runuser -u "$AUTOPKGTEST_NORMAL_USER" -- env CMD="mmdebstrap --setup-hook=$SRC/debian/tests/sourcesfilter --hook-dir=$SRC/hooks/file-mirror-automount" DEFAULT_DIST=$DEFAULT_DIST RUN_MA_SAME_TESTS=$RUN_MA_SAME_TESTS HAVE_QEMU=no HAVE_BINFMT=no USE_HOST_APT_CONFIG=yes "$SRC/coverage.sh" --exitfirst || ret=$?
-+timeout $TIMEOUT runuser -u "$AUTOPKGTEST_NORMAL_USER" -- env CMD="./mmdebstrap-under-test --setup-hook=$SRC/debian/tests/sourcesfilter --hook-dir=$SRC/hooks/file-mirror-automount" DEFAULT_DIST=$DEFAULT_DIST RUN_MA_SAME_TESTS=$RUN_MA_SAME_TESTS HAVE_QEMU=no HAVE_BINFMT=no USE_HOST_APT_CONFIG=yes "$SRC/coverage.sh" --exitfirst || ret=$?
++timeout $TIMEOUT runuser -u "$AUTOPKGTEST_NORMAL_USER" -- env CMD="./mmdebstrap --setup-hook=$SRC/debian/tests/sourcesfilter --hook-dir=$SRC/hooks/file-mirror-automount" DEFAULT_DIST=$DEFAULT_DIST RUN_MA_SAME_TESTS=$RUN_MA_SAME_TESTS HAVE_QEMU=no HAVE_BINFMT=no USE_HOST_APT_CONFIG=yes "$SRC/coverage.sh" --exitfirst || ret=$?
  if [ "$ret" -eq 124 ]; then
  	echo "command timed out after $TIMEOUT seconds" >&2
  	exit 77
